---
- name: Install nginx on server
  hosts: server2
  become: yes
  vars:
     servicename: nginx
  tasks:
    - name: Install nginx
      apt:
        name: "{{ servicename }}"
        state: latest

    - name: Start nginx
      service:
        name: "{{ servicename }}"
        state: started
        enabled: yes

