- name: Execute commands on target server without Python
  hosts: first
  become: yes
  gather_facts: no
  tasks:
    - name: Install package using raw command
      ansible.builtin.raw: apt install python3 -y  
      args:
        executable: /bin/bash 

